'use client';
import {useEffect,useRef,useState} from 'react';
import {Lock,Plus,Trash2,X} from 'lucide-react';
import {Action,Data,Expense,Line,Payload,Product,Sale,allocateFreight,saleBlockers,brl,canonicalCategory,categories,day,label,num,round} from '@/lib/domain';
import {ComboOption,Combobox} from './combobox';
export type ModalType='sale'|'batch'|'expense'|'product'|'adjust'|'whatsapp'|'cash';
type EntryType=Exclude<ModalType,'whatsapp'|'cash'>;
export function EntryForm({type,data,product,sale,expense,onSave,onClose,busy,error}:{type:EntryType;data:Data;product?:Product;sale?:Sale;expense?:Expense;onSave:(a:Action,p:Payload)=>Promise<boolean>;onClose:()=>void;busy:boolean;error:string}) {
 const dialog=useRef<HTMLDialogElement>(null);
 const saleItems=sale?data.sale_items.filter(i=>i.sale_id===sale.id):[];const reserved=(vid:string)=>saleItems.filter(i=>i.variant_id===vid).reduce((a,i)=>a+i.quantity,0);
 const itemsLocked=!!sale&&saleBlockers(data,sale.id,saleItems.map(i=>i.variant_id)).length>0;const blockersText=sale?saleBlockers(data,sale.id,saleItems.map(i=>i.variant_id)).join(', '):'';
 const [confirmDelete,setConfirmDelete]=useState(false);
 const [lines,setLines]=useState<Line[]>(sale?saleItems.map(i=>({variant_id:i.variant_id,quantity:i.quantity,unit_cost:0,unit_price:i.unit_price})):[{variant_id:'',quantity:1,unit_cost:0,unit_price:0}]);const [discount,setDiscount]=useState(sale?.discount??0);const [adjustVariant,setAdjustVariant]=useState('');
 const productOf=(vid:string)=>data.products.find(p=>p.id===data.variants.find(v=>v.id===vid)?.product_id);
 const variantOptions=(forSale:boolean):ComboOption[]=>[...data.variants].map(v=>({v,p:data.products.find(p=>p.id===v.product_id)})).sort((a,b)=>`${a.p?.model} ${a.v.name}`.localeCompare(`${b.p?.model} ${b.v.name}`,'pt-BR')).map(({v,p})=>({value:v.id,label:`${p?.model??'Produto'} · ${v.name}`,detail:`${v.quantity+(forSale?reserved(v.id):0)} un.${forSale?` · ${brl(p?.price??0)}`:''}${forSale&&v.quantity+reserved(v.id)===0?' · esgotado':''}`,keywords:`${p?.brand??''} ${p?.category??''}`,disabled:forSale&&v.quantity+reserved(v.id)===0}));
 const [deliveryCharged,setDeliveryCharged]=useState(sale?.delivery_charged??0);const [deliveryCost,setDeliveryCost]=useState(sale?.delivery_cost??0);
 const [freight,setFreight]=useState(0);const [payment,setPayment]=useState(sale?.payment??'Pix');const [fee,setFee]=useState(sale?.card_fee??0);const [adjustment,setAdjustment]=useState(-1);const [adjustType,setAdjustType]=useState<'perda'|'correcao'>('perda');
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 const purchase=type==='batch';const title={sale:sale?`Editar venda #${String(sale.number).padStart(3,'0')}`:'Registrar venda',batch:'Nova entrada de estoque',expense:expense?'Editar despesa':'Registrar despesa',product:product?'Editar produto':'Novo produto (sem estoque)',adjust:'Ajustar estoque'}[type];
 function update(index:number,field:keyof Line,value:string) {setLines(current=>current.map((l,i)=>{if(i!==index)return l;const next={...l,[field]:field==='variant_id'?value:Number(value)};if(field==='variant_id')next.unit_price=data.products.find(p=>p.id===data.variants.find(v=>v.id===value)?.product_id)?.price??0;return next;}));}
 const total=lines.reduce((a,l)=>a+l.quantity*(purchase?l.unit_cost??0:l.unit_price??0),0);
 let shares:number[]=[];try{shares=allocateFreight(lines,freight);}catch{}
 async function submit(e:React.FormEvent<HTMLFormElement>) {e.preventDefault();const f=new FormData(e.currentTarget);const text=(name:string)=>String(f.get(name)??'');const number=(name:string)=>Number(text(name));
  const payload:Payload= type==='product'?{id:product?.id,brand:text('brand'),model:text('model'),category:text('category'),price:number('price'),minimum:number('minimum'),variants:text('variants').split('\n').map(s=>s.trim()).filter(Boolean)}:
  type==='expense'?{id:expense?.id,category:text('category'),description:text('description'),amount:number('amount'),date:text('date')}:
  type==='adjust'?{variant_id:adjustVariant,adjustment_type:adjustType,quantity:adjustment,reason:text('reason'),unit_cost:number('unit_cost')}:
  purchase?{name:text('name'),freight,items:lines}:{sale_id:sale?.id,payment,discount:round(discount),delivery_charged:deliveryCharged,delivery_cost:deliveryCost,card_fee:['Débito','Crédito'].includes(payment)?fee:0,note:text('note'),items:lines.map(l=>({variant_id:l.variant_id,quantity:l.quantity,unit_price:l.unit_price}))};
  await onSave(sale?'update_sale':expense?'update_expense':({sale:'record_sale',batch:'record_batch',expense:'record_expense',product:'save_product',adjust:'adjust_stock'} as const)[type],payload);
 }
 return <dialog ref={dialog} className="modal" onCancel={e=>{e.preventDefault();if(!busy)onClose();}} aria-labelledby="modal-title"><form onSubmit={submit}><div className="modal-head"><div><span className="eyebrow">SEU DIA A DIA</span><h2 id="modal-title">{title}</h2></div><button type="button" className="icon-button" onClick={onClose} disabled={busy} aria-label="Fechar"><X size={20}/></button></div>
 {sale&&(itemsLocked?<div className="draft-note locked-note"><Lock size={15}/><span>Depois desta venda houve compra ou ajuste em {blockersText}. Para não alterar custos, aqui dá para mudar <strong>preço, desconto, pagamento e entrega</strong>. Para trocar sabor ou quantidade, exclua a venda e lance de novo.</span></div>:
  <div className="draft-note"><span>Mudando só preço, desconto, pagamento ou entrega, o custo (CMV) e o estoque não mudam. Trocando sabor ou quantidade, a venda é desfeita e lançada de novo. A versão anterior fica guardada.</span></div>)}
 <fieldset disabled={busy}>
 {type==='product'&&<><div className="form-grid"><label>Marca<input name="brand" required maxLength={80} defaultValue={product?.brand}/></label><label>Modelo / nome<input name="model" required maxLength={100} defaultValue={product?.model}/></label><label>Categoria<input name="category" required maxLength={80} list="tkm-categories-product" autoComplete="off" defaultValue={product?.category} onBlur={e=>{e.currentTarget.value=canonicalCategory(e.currentTarget.value,data.products.filter(p=>p.id!==product?.id));}}/><datalist id="tkm-categories-product">{categories(data.products).map(c=><option key={c.name} value={c.name}/>)}</datalist></label><label>Preço padrão (R$)<input name="price" type="number" min="0" step="0.01" required defaultValue={product?.price}/></label><label>Estoque mínimo por variedade<input name="minimum" type="number" min="0" step="1" required defaultValue={product?.minimum??2}/></label></div><label>{product?'Adicionar variedades (uma por linha)':'Variedades (uma por linha)'}<textarea name="variants" required={!product} placeholder={'Verde\nAreia\nAzul'} rows={3}/></label>{product&&<p className="hint">Variedades atuais: {data.variants.filter(v=>v.product_id===product.id).map(v=>v.name).join(', ')}. O histórico é preservado.</p>}</>}
 {(type==='sale'||purchase)&&<>{purchase?<div className="form-grid"><label>Nome da compra<input name="name" defaultValue="Compra" required/></label><label>Frete do lote (R$)<input type="number" min="0" step="0.01" required value={freight} onChange={e=>setFreight(Number(e.target.value))}/></label></div>:<div className="form-grid"><label>Forma de pagamento<select value={payment} onChange={e=>setPayment(e.target.value)}>{['Pix','Dinheiro','Débito','Crédito'].map(x=><option key={x}>{x}</option>)}</select></label>{['Débito','Crédito'].includes(payment)&&<label>Taxa repassada ao cliente (R$)<input type="number" min="0" step="0.01" value={fee} onChange={e=>setFee(Number(e.target.value))}/></label>}</div>}
 <div className="line-list">{lines.map((l,i)=><div className="item-line" key={i}>{purchase?<label>Produto e variedade<select required value={l.variant_id} onChange={e=>update(i,'variant_id',e.target.value)}><option value="" disabled>Selecione</option>{data.variants.map(v=><option key={v.id} value={v.id}>{label(data,v.id)} ({v.quantity} un.)</option>)}</select></label>:
 <fieldset className="inline-fieldset" disabled={itemsLocked}><Combobox label="Produto e sabor" required autoFocus={!sale&&i===lines.length-1&&i>0} placeholder="Digite o sabor ou o modelo…" options={variantOptions(true)} value={l.variant_id??''} onChange={v=>update(i,'variant_id',v)}/></fieldset>}<label>Qtd.<input type="number" min="1" step="1" required disabled={itemsLocked} value={l.quantity} onChange={e=>update(i,'quantity',e.target.value)}/></label><label>{purchase?'Custo un. (R$)':'Preço un. (R$)'}<input type="number" min={purchase?'0.01':'0'} step="0.01" required value={purchase?l.unit_cost:l.unit_price} onChange={e=>update(i,purchase?'unit_cost':'unit_price',e.target.value)}/></label><button className="icon-button" type="button" aria-label={`Remover item ${i+1}`} disabled={lines.length===1||itemsLocked} onClick={()=>setLines(lines.filter((_,j)=>j!==i))}><Trash2 size={16}/></button>{!purchase&&l.variant_id&&productOf(l.variant_id)&&Math.abs((l.unit_price??0)-productOf(l.variant_id)!.price)>=0.005&&<small className="allocation list-diff">Preço de tabela {brl(productOf(l.variant_id)!.price)} · {(l.unit_price??0)<productOf(l.variant_id)!.price?`${brl(productOf(l.variant_id)!.price-(l.unit_price??0))} abaixo da tabela por unidade (conta como desconto)`:'acima da tabela'}</small>}{purchase&&shares.length>0&&<small className="allocation">Frete: {brl(shares[i])} · Total do item: {brl(l.quantity*(l.unit_cost??0)+shares[i])}</small>}</div>)}</div>
 <button type="button" className="button secondary" disabled={itemsLocked} onClick={()=>setLines([...lines,{variant_id:'',quantity:1,unit_cost:0,unit_price:0}])}><Plus size={16}/>Adicionar item</button>
 {!purchase&&<div className="delivery-fields"><h3>Transporte / entrega</h3><div className="form-grid"><label>Entrega cobrada do cliente (R$)<input type="number" min="0" step="0.01" required value={deliveryCharged} onChange={e=>setDeliveryCharged(Number(e.target.value))}/></label><label>Custo da entrega para você (R$)<input type="number" min="0" step="0.01" required value={deliveryCost} onChange={e=>setDeliveryCost(Number(e.target.value))}/></label></div><p className="hint">Resultado do transporte: <strong className={deliveryCharged>=deliveryCost?'positive':'negative'}>{brl(deliveryCharged-deliveryCost)}</strong>. O custo será lançado automaticamente em Despesas, vinculado a esta venda. Não lance novamente.</p></div>}
 {!purchase&&<label>Observação (opcional)<input name="note" maxLength={300} defaultValue={sale?.note??''} placeholder="Ex.: promoção de lançamento"/></label>}
 {!purchase&&(()=>{const list=lines.reduce((a,l)=>a+l.quantity*(l.variant_id?productOf(l.variant_id)?.price??l.unit_price??0:0),0);const priceDiff=lines.reduce((a,l)=>a+Math.max(0,l.quantity*((l.variant_id?productOf(l.variant_id)?.price??0:0)-(l.unit_price??0))),0);
  const net=total-discount;const cmv=lines.reduce((a,l)=>{const orig=saleItems.find(i=>i.variant_id===l.variant_id&&i.quantity===l.quantity);if(orig)return a+orig.cogs;const v=data.variants.find(x=>x.id===l.variant_id);return a+(v&&v.quantity?v.value/v.quantity*l.quantity:0);},0);const margin=net>0?(net-cmv)/net*100:0;
  return <div className="sale-summary">
   <label className="discount-field">Desconto na venda (R$)<input type="number" min="0" step="0.01" max={total||undefined} value={discount||''} placeholder="0,00" onChange={e=>setDiscount(Number(e.target.value))}/></label>
   <dl><div><dt>Produtos pela tabela</dt><dd>{brl(list)}</dd></div>
    {priceDiff>0.004&&<div><dt>Preço abaixo da tabela</dt><dd className="negative">− {brl(priceDiff)}</dd></div>}
    {discount>0&&<div><dt>Desconto na venda</dt><dd className="negative">− {brl(discount)}</dd></div>}
    <div className="strong"><dt>Produtos (líquido)</dt><dd>{brl(net)}</dd></div>
    {cmv>0&&<div className="muted-row"><dt>Lucro bruto estimado</dt><dd className={net-cmv>=0?'positive':'negative'}>{brl(net-cmv)} · margem {num(margin)}%</dd></div>}</dl>
   {discount>total+0.004&&<p className="error">O desconto é maior que o valor dos produtos.</p>}
  </div>;})()}
 <div className="form-total"><span>{purchase?'Custo total com frete':'Total cobrado do cliente'}</span><strong>{brl(total+(purchase?freight:deliveryCharged-discount+(['Débito','Crédito'].includes(payment)?fee:0)))}</strong></div><p className="hint">{purchase?'O frete será distribuído proporcionalmente ao valor da mercadoria.':'O desconto vale só para os produtos e é dividido entre os itens pelo valor de cada um. Entrega e taxa repassada não recebem desconto; a taxa não entra no faturamento.'}</p></>}
 {type==='expense'&&<><div className="form-grid"><label>Categoria<select name="category" defaultValue={expense?.category}>{['Anúncios','Entrega','Embalagem','Ferramentas/sistemas','Outros'].map(x=><option key={x}>{x}</option>)}</select></label><label>Data<input name="date" type="date" required defaultValue={expense?.date??day()}/></label></div><label>Descrição<input name="description" required maxLength={200} defaultValue={expense?.description} placeholder="Ex.: campanha da semana"/></label><label>Valor (R$)<input name="amount" type="number" min="0.01" step="0.01" required defaultValue={expense?.amount}/></label><p className="hint">Compra de mercadoria não é despesa: lance em Entradas / Lotes → Nova compra (o custo entra no estoque e vira CMV quando você vende).</p></>}
 {type==='adjust'&&<><Combobox label="Produto e sabor" required placeholder="Digite o sabor ou o modelo…" options={variantOptions(false)} value={adjustVariant} onChange={setAdjustVariant}/><div className="form-grid"><label>Quantidade do ajuste<input type="number" step="1" required value={adjustment} onChange={e=>setAdjustment(Number(e.target.value))}/></label>{adjustment>0&&<label>Custo unitário das unidades adicionadas (R$)<input name="unit_cost" type="number" step="0.01" min="0" required/></label>}</div><div className="adjust-type" role="radiogroup" aria-label="Tipo de ajuste">{([['perda','Perda / avaria','Entra como perda no resultado'],['correcao','Correção de lançamento','Corrige o estoque sem contar como perda']] as const).map(([k,t,d])=><label key={k} className={adjustType===k?'active':''}><input type="radio" name="adjust_type" checked={adjustType===k} onChange={()=>setAdjustType(k)}/><span><strong>{t}</strong><small>{d}</small></span></label>)}</div>
 <p className="hint">Somente para perda, avaria, divergência de inventário ou correção. Reposição normal entra por Entradas / Lotes → Nova compra. Use −1 para retirar uma unidade; retiradas usam o custo médio e aparecem como perdas no resultado.</p><label>Motivo<input name="reason" required minLength={3} maxLength={200} placeholder="Ex.: avaria identificada na contagem"/></label></>}
 </fieldset>{error&&<p className="error" role="alert">{error}</p>}<div className="modal-footer">{sale&&<button type="button" className={`button secondary danger-button${confirmDelete?' confirming':''}`} disabled={busy} onClick={async()=>{if(!confirmDelete){setConfirmDelete(true);return;}await onSave('delete_sale',{sale_id:sale.id});}}><Trash2 size={15}/>{confirmDelete?'Confirmar exclusão da venda':'Excluir venda'}</button>}<span className="footer-spacer"/><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="button" disabled={busy||(type!=='product'&&type!=='expense'&&!data.variants.length)}>{busy?'Salvando…':sale?'Salvar alterações':'Confirmar registro'}</button></div>
 {confirmDelete&&<p className="hint delete-hint">A venda some do faturamento, as unidades voltam ao estoque pelo mesmo custo e a despesa de entrega vinculada é removida. Clique de novo para confirmar.</p>}</form></dialog>;
}
