'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Trash2,X} from 'lucide-react';
import {Action,Data,Line,Payload,Product,allocateFreight,brl,canonicalCategory,categories,day,label} from '@/lib/domain';
export type ModalType='sale'|'batch'|'expense'|'product'|'adjust';
export function EntryForm({type,data,product,onSave,onClose,busy,error}:{type:ModalType;data:Data;product?:Product;onSave:(a:Action,p:Payload)=>Promise<boolean>;onClose:()=>void;busy:boolean;error:string}) {
 const dialog=useRef<HTMLDialogElement>(null);
 const [lines,setLines]=useState<Line[]>([{variant_id:data.variants[0]?.id??'',quantity:1,unit_cost:0,unit_price:data.products.find(p=>p.id===data.variants[0]?.product_id)?.price??0}]);
 const [deliveryCharged,setDeliveryCharged]=useState(0);const [deliveryCost,setDeliveryCost]=useState(0);
 const [freight,setFreight]=useState(0);const [payment,setPayment]=useState('Pix');const [fee,setFee]=useState(0);const [adjustment,setAdjustment]=useState(-1);
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 const purchase=type==='batch';const title={sale:'Registrar venda',batch:'Nova entrada de estoque',expense:'Registrar despesa',product:product?'Editar produto':'Novo produto (sem estoque)',adjust:'Ajustar estoque'}[type];
 function update(index:number,field:keyof Line,value:string) {setLines(current=>current.map((l,i)=>{if(i!==index)return l;const next={...l,[field]:field==='variant_id'?value:Number(value)};if(field==='variant_id')next.unit_price=data.products.find(p=>p.id===data.variants.find(v=>v.id===value)?.product_id)?.price??0;return next;}));}
 const total=lines.reduce((a,l)=>a+l.quantity*(purchase?l.unit_cost??0:l.unit_price??0),0);
 let shares:number[]=[];try{shares=allocateFreight(lines,freight);}catch{}
 async function submit(e:React.FormEvent<HTMLFormElement>) {e.preventDefault();const f=new FormData(e.currentTarget);const text=(name:string)=>String(f.get(name)??'');const number=(name:string)=>Number(text(name));
  const payload:Payload= type==='product'?{id:product?.id,brand:text('brand'),model:text('model'),category:text('category'),price:number('price'),minimum:number('minimum'),variants:text('variants').split('\n').map(s=>s.trim()).filter(Boolean)}:
  type==='expense'?{category:text('category'),description:text('description'),amount:number('amount'),date:text('date')}:
  type==='adjust'?{variant_id:text('variant_id'),quantity:adjustment,reason:text('reason'),unit_cost:number('unit_cost')}:
  purchase?{name:text('name'),freight,items:lines}:{payment,delivery_charged:deliveryCharged,delivery_cost:deliveryCost,card_fee:['Débito','Crédito'].includes(payment)?fee:0,note:text('note'),items:lines};
  await onSave(({sale:'record_sale',batch:'record_batch',expense:'record_expense',product:'save_product',adjust:'adjust_stock'} as const)[type],payload);
 }
 return <dialog ref={dialog} className="modal" onCancel={e=>{e.preventDefault();if(!busy)onClose();}} aria-labelledby="modal-title"><form onSubmit={submit}><div className="modal-head"><div><span className="eyebrow">SEU DIA A DIA</span><h2 id="modal-title">{title}</h2></div><button type="button" className="icon-button" onClick={onClose} disabled={busy} aria-label="Fechar"><X size={20}/></button></div>
 <fieldset disabled={busy}>
 {type==='product'&&<><div className="form-grid"><label>Marca<input name="brand" required maxLength={80} defaultValue={product?.brand}/></label><label>Modelo / nome<input name="model" required maxLength={100} defaultValue={product?.model}/></label><label>Categoria<input name="category" required maxLength={80} list="tkm-categories-product" autoComplete="off" defaultValue={product?.category} onBlur={e=>{e.currentTarget.value=canonicalCategory(e.currentTarget.value,data.products.filter(p=>p.id!==product?.id));}}/><datalist id="tkm-categories-product">{categories(data.products).map(c=><option key={c.name} value={c.name}/>)}</datalist></label><label>Preço padrão (R$)<input name="price" type="number" min="0" step="0.01" required defaultValue={product?.price}/></label><label>Estoque mínimo por variedade<input name="minimum" type="number" min="0" step="1" required defaultValue={product?.minimum??2}/></label></div><label>{product?'Adicionar variedades (uma por linha)':'Variedades (uma por linha)'}<textarea name="variants" required={!product} placeholder={'Verde\nAreia\nAzul'} rows={3}/></label>{product&&<p className="hint">Variedades atuais: {data.variants.filter(v=>v.product_id===product.id).map(v=>v.name).join(', ')}. O histórico é preservado.</p>}</>}
 {(type==='sale'||purchase)&&<>{purchase?<div className="form-grid"><label>Nome da compra<input name="name" defaultValue="Compra" required/></label><label>Frete do lote (R$)<input type="number" min="0" step="0.01" required value={freight} onChange={e=>setFreight(Number(e.target.value))}/></label></div>:<div className="form-grid"><label>Forma de pagamento<select value={payment} onChange={e=>setPayment(e.target.value)}>{['Pix','Dinheiro','Débito','Crédito'].map(x=><option key={x}>{x}</option>)}</select></label>{['Débito','Crédito'].includes(payment)&&<label>Taxa repassada ao cliente (R$)<input type="number" min="0" step="0.01" value={fee} onChange={e=>setFee(Number(e.target.value))}/></label>}</div>}
 <div className="line-list">{lines.map((l,i)=><div className="item-line" key={i}><label>Produto e variedade<select required value={l.variant_id} onChange={e=>update(i,'variant_id',e.target.value)}><option value="" disabled>Selecione</option>{data.variants.map(v=><option key={v.id} value={v.id}>{label(data,v.id)} ({v.quantity} un.)</option>)}</select></label><label>Qtd.<input type="number" min="1" step="1" required value={l.quantity} onChange={e=>update(i,'quantity',e.target.value)}/></label><label>{purchase?'Custo un. (R$)':'Preço un. final (R$)'}<input type="number" min={purchase?'0.01':'0'} step="0.01" required value={purchase?l.unit_cost:l.unit_price} onChange={e=>update(i,purchase?'unit_cost':'unit_price',e.target.value)}/></label><button className="icon-button" type="button" aria-label={`Remover item ${i+1}`} disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,j)=>j!==i))}><Trash2 size={16}/></button>{purchase&&shares.length>0&&<small className="allocation">Frete: {brl(shares[i])} · Total do item: {brl(l.quantity*(l.unit_cost??0)+shares[i])}</small>}</div>)}</div>
 <button type="button" className="button secondary" onClick={()=>setLines([...lines,{variant_id:'',quantity:1,unit_cost:0,unit_price:0}])}><Plus size={16}/>Adicionar item</button>
 {!purchase&&<div className="delivery-fields"><h3>Transporte / entrega</h3><div className="form-grid"><label>Entrega cobrada do cliente (R$)<input type="number" min="0" step="0.01" required value={deliveryCharged} onChange={e=>setDeliveryCharged(Number(e.target.value))}/></label><label>Custo da entrega para você (R$)<input type="number" min="0" step="0.01" required value={deliveryCost} onChange={e=>setDeliveryCost(Number(e.target.value))}/></label></div><p className="hint">Resultado do transporte: <strong className={deliveryCharged>=deliveryCost?'positive':'negative'}>{brl(deliveryCharged-deliveryCost)}</strong>. O custo será lançado automaticamente em Despesas, vinculado a esta venda. Não lance novamente.</p></div>}
 {!purchase&&<label>Observação (opcional)<input name="note" maxLength={300} placeholder="Ex.: promoção de lançamento"/></label>}
 <div className="form-total"><span>{purchase?'Custo total com frete':'Total cobrado do cliente'}</span><strong>{brl(total+(purchase?freight:deliveryCharged+(['Débito','Crédito'].includes(payment)?fee:0)))}</strong></div><p className="hint">{purchase?'O frete será distribuído proporcionalmente ao valor da mercadoria.':'O preço pode ser alterado por item. A taxa repassada não entra no faturamento nem nas despesas.'}</p></>}
 {type==='expense'&&<><div className="form-grid"><label>Categoria<select name="category">{['Anúncios','Entrega','Embalagem','Ferramentas/sistemas','Outros'].map(x=><option key={x}>{x}</option>)}</select></label><label>Data<input name="date" type="date" required defaultValue={day()}/></label></div><label>Descrição<input name="description" required maxLength={200} placeholder="Ex.: campanha da semana"/></label><label>Valor (R$)<input name="amount" type="number" min="0.01" step="0.01" required/></label></>}
 {type==='adjust'&&<><label>Produto e variedade<select name="variant_id" required>{data.variants.map(v=><option key={v.id} value={v.id}>{label(data,v.id)} ({v.quantity} un.)</option>)}</select></label><div className="form-grid"><label>Quantidade do ajuste<input type="number" step="1" required value={adjustment} onChange={e=>setAdjustment(Number(e.target.value))}/></label>{adjustment>0&&<label>Custo unitário das unidades adicionadas (R$)<input name="unit_cost" type="number" step="0.01" min="0" required/></label>}</div><p className="hint">Somente para perda, avaria, divergência de inventário ou correção. Reposição normal entra por Entradas / Lotes → Nova compra. Use −1 para retirar uma unidade; retiradas usam o custo médio e aparecem como perdas no resultado.</p><label>Motivo<input name="reason" required minLength={3} maxLength={200} placeholder="Ex.: avaria identificada na contagem"/></label></>}
 </fieldset>{error&&<p className="error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="button" disabled={busy||(type!=='product'&&type!=='expense'&&!data.variants.length)}>{busy?'Salvando…':'Confirmar registro'}</button></div></form></dialog>;
}
