'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,BarChart3,Boxes,Check,ChevronRight,Download,History,LayoutDashboard,LogOut,Package,Plus,RefreshCw,Search,ShoppingBag,MessageCircle,Landmark,Sparkles,TrendingUp,Truck,Wallet,X} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {Action,Batch,CashKind,Data,Expense,Payload,Product,Sale,cashFlow,applyAction,brl,categories,categoryKey,itemDiscount,dateBR,day,demoData,emptyData,exportCSV,label,num,report} from '@/lib/domain';
import {EntryForm,ModalType} from './forms';
import {PurchaseForm} from './purchase';
import {WhatsappList} from './whatsapp';
import {CashForm} from './cash';
import Brand from './brand';
const sections=[['Dashboard',LayoutDashboard],['Estoque',Boxes],['Entradas / Lotes',Truck],['Vendas',ShoppingBag],['Financeiro',Landmark],['Relatórios',BarChart3],['Histórico',History]] as const;
type Section=typeof sections[number][0];
const descriptions:Record<Section,string>={Dashboard:'Tudo o que importa, em um só lugar.',Estoque:'Cada produto, cada variedade, sempre à mão.','Entradas / Lotes':'Toda reposição começa aqui: compra, produtos e estoque.',Vendas:'Suas vendas, do primeiro item ao resultado.',Financeiro:'Caixa, despesas e empréstimos em um só lugar.',Relatórios:'Descubra quais produtos fazem a diferença.',Histórico:'Um registro de cada movimento do seu estoque.'};
const DEMO_KEY='clara-demo-v1';
function Metric({title,value,detail,accent=false}:{title:string;value:string;detail?:string;accent?:boolean}) {return <div className={`metric ${accent?'accent':''}`}><span>{title}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;}
function Empty({text='Nenhum registro por aqui ainda.'}:{text?:string}) {return <div className="empty"><Package size={28}/><p>{text}</p></div>;}
export default function Workspace() {
 const [data,setData]=useState<Data>(emptyData());const [mode,setMode]=useState<'loading'|'login'|'demo'|'live'>('loading');const [section,setSection]=useState<Section>('Dashboard');
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [authBusy,setAuthBusy]=useState(false);
 const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);
 const [modal,setModal]=useState<ModalType|null>(null);const [editing,setEditing]=useState<Product>();const [editingBatch,setEditingBatch]=useState<Batch>();const [editingSale,setEditingSale]=useState<Sale>();const [editingExpense,setEditingExpense]=useState<Expense>();const [cashPreset,setCashPreset]=useState<{kind?:CashKind;loan?:string}>({});const [confirming,setConfirming]=useState('');const [finFilter,setFinFilter]=useState<'tudo'|'despesas'|'vendas'|'compras'|'emprestimos'|'aportes'>('tudo');const [modalError,setModalError]=useState('');
 const [from,setFrom]=useState('');const [to,setTo]=useState('');const [query,setQuery]=useState('');const [stockStatus,setStockStatus]=useState<'todos'|'com'|'baixo'|'esgotado'>('todos');const [brand,setBrand]=useState('');const [category,setCategory]=useState('');const [kind,setKind]=useState('Todos');
 const [preset,setPreset]=useState('all');const [rankBy,setRankBy]=useState<'modelo'|'marca'|'sabor'>('modelo');const [sort,setSort]=useState<'units'|'revenue'|'profit'|'margin'|'turnover'>('units');const [expenseFilter,setExpenseFilter]=useState('Todas');
 const pending=useRef<string|null>(null);const saving=useRef(false);const mounted=useRef(true);
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);try{const {data:state,error:e}=await supabase.rpc('get_state');if(e)throw e;if(mounted.current)setData(state as Data);}finally{if(mounted.current)setLoading(false);}},[]);
 useEffect(()=>{mounted.current=true;if(!supabase){setMode('login');return;}supabase.auth.getSession().then(async({data:{session},error:e})=>{if(e)setError(e.message);if(!mounted.current)return;setMode(session?'live':'login');if(session)try{await load();}catch(e){setError((e as Error).message);}});const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){setData(emptyData());setMode('login');}if(event==='SIGNED_IN'&&session)setMode('live');});return()=>{mounted.current=false;subscription.unsubscribe();};},[load]);
 // Rolagem do mouse não altera campos numéricos: o valor só muda quando você digita.
 useEffect(()=>{const guard=(e:WheelEvent)=>{const el=document.activeElement;if(el instanceof HTMLInputElement&&el.type==='number'&&el===e.target)el.blur();};document.addEventListener('wheel',guard,{passive:true});return()=>document.removeEventListener('wheel',guard);},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(timer);},[notice]);
 const r=useMemo(()=>report(data,from,to),[data,from,to]);
 function open(type:ModalType,product?:Product,batch?:Batch,sale?:Sale,expense?:Expense){pending.current=null;setModalError('');setEditing(product);setEditingBatch(batch);setEditingSale(sale);setEditingExpense(expense);setModal(type);}
 function startDemo(){try{const saved=localStorage.getItem(DEMO_KEY);setData(saved?JSON.parse(saved):demoData());setMode('demo');setError('');}catch{setData(demoData());setMode('demo');setNotice('Uma nova demonstração foi iniciada.');}}
 async function login(e:React.FormEvent){e.preventDefault();if(!supabase)return;setAuthBusy(true);setError('');try{const {error:e}=await supabase.auth.signInWithPassword({email,password});if(e)throw e;setPassword('');setMode('live');await load();}catch(e){setError((e as Error).message);}finally{setAuthBusy(false);}}
 async function logout(){if(mode==='live'&&supabase){const {error:e}=await supabase.auth.signOut();if(e){setError(e.message);return;}}setData(emptyData());setMode('login');setError('');}
 async function save(action:Action,p:Payload):Promise<boolean>{if(saving.current)return false;saving.current=true;setBusy(true);setModalError('');const request_id=pending.current??crypto.randomUUID();pending.current=request_id;
  try{if(mode==='demo'){const next=applyAction(data,action,{...p,request_id});localStorage.setItem(DEMO_KEY,JSON.stringify(next));setData(next);}else{if(!supabase)throw Error('Supabase não configurado.');const {error:e}=await supabase.rpc(action,{p:{...p,request_id}});if(e)throw e;try{await load();}catch{setError('Registro salvo, mas a atualização da tela falhou. Clique em Atualizar antes de continuar.');}}
   setModal(null);pending.current=null;setNotice(({record_purchase:'Compra finalizada. Estoque e custos atualizados.',update_purchase:'Compra corrigida. Estoque e custos recalculados.',rename_purchase:'Nome e data da compra atualizados.',delete_purchase:'Compra excluída. Estoque atualizado.',update_sale:'Venda corrigida.',save_list_settings:'Personalização da lista salva.',record_cash_entry:'Lançamento de caixa registrado.',cancel_cash_entry:'Lançamento de caixa excluído.',update_expense:'Despesa corrigida.',cancel_expense:'Despesa excluída.',delete_sale:'Venda excluída. Estoque devolvido.'} as Record<string,string>)[action]??'Registro salvo com sucesso.');return true;
  }catch(e){setModalError((e as Error).message);return false;}finally{saving.current=false;setBusy(false);}}
 async function refresh(){setError('');try{await load();setNotice('Dados atualizados.');}catch(e){setError((e as Error).message);}}
 function period(value:string){const today=day();setPreset(value);if(value==='all'){setFrom('');setTo('');return;}setTo(today);if(value==='month'){setFrom(today.slice(0,7)+'-01');return;}const days=value==='15'?15:7;const d=new Date(today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(days-1));setFrom(day(d));}
 const categoryList=categories(data.products);const inCategory=(c:string)=>!category||categoryKey(c||'Geral')===category;
 const brandList=[...new Set(data.products.map(p=>p.brand.trim()))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
 const q=categoryKey(query);
 const statusOf=(v:{quantity:number},p:Product)=>v.quantity===0?'esgotado':v.quantity<=p.minimum?'baixo':'com';
 /** Sabores visíveis: busca por marca/modelo/categoria mostra o produto inteiro; busca pelo sabor mostra só os sabores encontrados. */
 const visibleVariants=(p:Product)=>{const productMatch=!q||categoryKey(`${p.brand} ${p.model} ${p.category}`).includes(q);
  return data.variants.filter(v=>v.product_id===p.id&&(productMatch||categoryKey(v.name).includes(q))&&(stockStatus==='todos'||(stockStatus==='com'?v.quantity>0:statusOf(v,p)===stockStatus))).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));};
 const filteredProducts=data.products.filter(p=>inCategory(p.category)&&(!brand||p.brand.trim()===brand)&&visibleVariants(p).length>0);
 const filteredUnits=filteredProducts.reduce((a,p)=>a+visibleVariants(p).reduce((b,v)=>b+v.quantity,0),0);
 const filtersOn=!!(query||category||brand||stockStatus!=='todos');
 const ranking=[...r.rows].filter(p=>inCategory(p.category)).sort((a,b)=>(b[sort]??-1)-(a[sort]??-1));
 const csv=()=>exportCSV(ranking.map(p=>({Produto:p.model,Marca:p.brand,Categoria:p.category,Unidades:p.units,Faturamento:brl(p.revenue),Lucro:brl(p.profit),'Margem (%)':num(p.margin),Giro:p.turnover===null?'—':num(p.turnover),'Variedade mais vendida':p.best,'Última venda':p.last?dateBR(p.last):'Nunca','Dias sem venda':p.days??'—','Estoque atual':p.stock})),`performance-${category?categoryKey(category).replace(/\s+/g,'-')+'-':''}${day()}.csv`);
 const categoryFilter=(compact=false)=> <label className={compact?'sort-label':'category-filter'}>Categoria<select aria-label="Filtrar por categoria" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas ({data.products.length})</option>{categoryList.map(c=><option key={c.name} value={categoryKey(c.name)}>{c.name} ({c.count})</option>)}</select></label>;
 if(mode==='loading')return <main className="loading"><RefreshCw className="spin"/><p>Abrindo seu espaço…</p></main>;
 if(mode==='login')return <main className="login-page"><section className="login-story"><div className="login-signature"><span className="brand-name">TKM SMOKE</span><span className="login-system-label">ESTOQUE & FINANCEIRO</span></div><div className="login-brand-stage"><Brand hero/></div><div className="login-story-copy"><span className="eyebrow">ATITUDE NA MARCA. CLAREZA NA GESTÃO.</span><h1>Seu negócio.<br/> Seu controle.</h1><p>Estoque, vendas e resultados.<br/>Tudo no mesmo lugar.</p></div><small>TKM SMOKE <span>•</span> Seu espaço de gestão.</small></section><section className="login-panel"><div><span className="eyebrow">BEM-VINDA À TKM SMOKE</span><h2>Acesse seu espaço.</h2><p className="muted">Entre com a conta compartilhada do seu negócio.</p>{supabase?<form onSubmit={login}><label>E-mail<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com"/></label><label>Senha<input type="password" autoComplete="current-password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button wide" disabled={authBusy}>{authBusy?'Entrando…':'Entrar no meu espaço'}<ArrowUpRight size={17}/></button></form>:<div className="setup-note">O ambiente está pronto para demonstração. Para usar dados reais, configure o Supabase conforme o guia do projeto.</div>}{error&&<p className="error" role="alert">{error}</p>}<div className="or"><span/>ou conheça primeiro<span/></div><button className="button secondary wide" onClick={startDemo}><Sparkles size={17}/>Explorar demonstração</button><p className="hint centered">Papelaria fictícia · Dados salvos apenas neste navegador</p></div></section></main>;
 return <div className="app-shell"><aside className="sidebar"><Brand/><div className="workspace-label"><span className="avatar">{mode==='demo'?'D':'T'}</span><div><strong>{mode==='demo'?'Demonstração':'TKM SMOKE'}</strong><small>{mode==='demo'?'Ambiente de demonstração':'Estoque e financeiro'}</small></div></div><span className="nav-label">ESPAÇO DE TRABALHO</span><nav aria-label="Menu principal">{sections.map(([name,Icon])=><button key={name} aria-label={name} title={name} className={section===name?'selected':''} onClick={()=>{setSection(name);setQuery('');}} aria-current={section===name?'page':undefined}><Icon size={19}/><span>{name}</span>{section===name&&<span className="active-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><span className="status-dot"/><span>{mode==='demo'?'Demonstração local':'Conectado ao Supabase'}</span></div><button onClick={logout}><LogOut size={17}/>Sair do espaço</button></div></aside>
 <main className="main"><header className="topbar"><div><span className="breadcrumb">TKM SMOKE</span><ChevronRight size={14}/><strong>{section}</strong></div><div className="topbar-right"><span>{dateBR(day())}</span>{mode==='live'&&<button className="icon-button" disabled={loading} onClick={refresh} aria-label="Atualizar dados"><RefreshCw size={17} className={loading?'spin':''}/></button>}<button className="icon-button" onClick={logout} aria-label="Sair"><LogOut size={16}/></button><span className="avatar small">{mode==='demo'?'D':'T'}</span></div></header>
 <div className="page-content">{mode==='demo'&&<div className="demo-banner"><Sparkles size={16}/><span>Você está explorando uma papelaria fictícia. Alterações ficam neste navegador.</span><button onClick={()=>{localStorage.removeItem(DEMO_KEY);setData(demoData());setNotice('Demonstração reiniciada.');}}>Reiniciar demo</button></div>}
 <div className="page-heading"><div><span className="eyebrow">{section==='Dashboard'?'VISÃO GERAL':'GESTÃO DO NEGÓCIO'}</span><h1>{section==='Dashboard'?'Seu negócio em foco.':section}</h1><p>{descriptions[section]}</p></div><div className="actions">{section==='Estoque'?<><button className="button secondary" onClick={()=>open('whatsapp')} disabled={!data.variants.length}><MessageCircle size={17}/>Lista para o grupo</button><button className="button secondary" onClick={()=>open('adjust')} disabled={!data.variants.length}>Ajustar estoque</button><button className="button secondary" onClick={()=>open('product')}><Plus size={17}/>Novo produto</button><button className="button" onClick={()=>open('batch')}><Truck size={17}/>Nova compra</button></>:section==='Relatórios'?<button className="button secondary" onClick={csv} disabled={!ranking.length}><Download size={16}/>Exportar CSV</button>:section==='Financeiro'?<button className="button" onClick={()=>{setCashPreset({});open('cash');}}><Plus size={17}/>Novo lançamento</button>:section!=='Histórico'&&<button className="button" onClick={()=>open(section==='Entradas / Lotes'?'batch':'sale')}><Plus size={17}/>{section==='Entradas / Lotes'?'Nova compra':'Nova venda'}</button>}</div></div>
 {error&&<div className="error" role="alert">{error}<button className="icon-button" aria-label="Fechar aviso" onClick={()=>setError('')}><X size={16}/></button></div>}
 {section!=='Estoque'&&<div className="period-bar"><span>Período</span>{([['all','Tudo'],['month','Este mês'],['15','15 dias'],['7','7 dias']] as const).map(([k,t])=><button key={k} onClick={()=>period(k)} className={preset===k?'period-active':''} aria-pressed={preset===k}>{t}</button>)}<div className={`date-range${preset==='custom'?' custom-active':''}`}><span className="range-label">Personalizado</span><input aria-label="Data inicial" type="date" value={from} max={to||day()} onChange={e=>{setFrom(e.target.value);setPreset('custom');}}/><span>até</span><input aria-label="Data final" type="date" value={to} min={from||undefined} max={day()} onChange={e=>{setTo(e.target.value);setPreset('custom');}}/></div></div>}
 {from&&to&&from>to?<div className="error">A data inicial deve ser anterior à data final.</div>:<>
 {section==='Dashboard'&&<><div className="hero-grid"><div className="result-card"><div><span>Resultado líquido do período</span><span className="hero-icon"><TrendingUp size={21}/></span></div><strong>{brl(r.net)}</strong><p>Depois do custo dos produtos, despesas, resultado das entregas e perdas.</p><footer><span>Margem líquida <b>{num(r.revenue?r.net/r.revenue*100:0)}%</b></span><span>{num(r.units)} unidades vendidas</span></footer></div><div className="metrics-grid six"><Metric title="Faturamento" value={brl(r.revenue)} detail={r.discounts>0?`Tabela ${brl(r.grossProducts)} − descontos`:'Produtos vendidos'}/><Metric title="Descontos concedidos" value={brl(r.discounts)} detail={r.grossProducts?`${num(r.discounts/r.grossProducts*100)}% sobre o preço de tabela`:'Sobre o preço de tabela'}/><Metric title="Ticket médio" value={brl(r.sales.length?r.revenue/r.sales.length:0)} detail={`${r.sales.length} venda${r.sales.length===1?'':'s'} no período`}/><Metric title="Lucro bruto" value={brl(r.gross)} detail="Faturamento − custo vendido"/><Metric title="Despesas" value={brl(r.operatingExpense)} detail="Operacionais · entregas ficam em Transporte"/><Metric title="Capital recuperado" value={brl(r.cogs)} detail="Custo das mercadorias vendidas"/></div></div>
 {(()=>{const c=cashFlow(data);return <><div className="section-heading"><h2>Seu caixa, agora</h2><span>{c.start?`Saldo atual · independente do período`:'Lance o saldo inicial na aba Financeiro'}</span></div><div className="stock-metrics three cash-strip">
  <button className="metric-link" onClick={()=>setSection('Financeiro')}><Metric title="Saldo em caixa" value={brl(c.balance)} detail={c.start?'Dinheiro disponível hoje · ver extrato':'Configure na aba Financeiro'}/></button>
  <Metric title="Empréstimos em aberto" value={brl(c.debt)} detail={c.debt>0?'Quanto a empresa ainda deve':'Nenhuma dívida'}/>
  <Metric title="Caixa + estoque − dívidas" value={brl(c.balance+r.capital-c.debt)} detail="Quanto o negócio vale hoje, a custo"/></div></>;})()}
 <div className="section-heading"><h2>Transporte no período</h2><span>Repasse ao cliente · fora do faturamento</span></div><div className="stock-metrics three"><Metric title="Entrega cobrada dos clientes" value={brl(r.deliveryRevenue)} detail="Repassada ao entregador"/><Metric title="Custo das entregas" value={brl(r.deliveryCost)} detail="Pago pelas entregas"/><Metric title="Resultado do transporte" value={brl(r.deliveryProfit)} detail={r.deliveryProfit>=0?'Cobrado menos pago · entra no resultado':'Você pagou mais do que cobrou · entra no resultado'}/></div>
 <div className="section-heading"><h2>Seu estoque, agora</h2><span>Posição atual · independente do período</span></div><div className="stock-metrics"><Metric title="Unidades em estoque" value={num(r.stock)} detail={`${data.products.length} produtos · ${data.variants.length} variedades`}/><Metric title="Capital em estoque" value={brl(r.capital)} detail="Custo médio com frete"/><Metric title="Venda potencial" value={brl(r.potential)} detail="Aos preços padrão atuais"/><Metric title="Lucro bruto potencial" value={brl(r.potential-r.capital)} detail="Antes de futuras despesas"/></div>
 <div className="bottom-grid"><section className="panel"><div className="panel-heading"><div><h2>Mais vendidos</h2><p>Ranking do período por unidades</p></div><div className="segmented" role="tablist" aria-label="Ranking por">{(['modelo','marca','sabor'] as const).map(k=><button key={k} role="tab" aria-selected={rankBy===k} className={rankBy===k?'active':''} onClick={()=>setRankBy(k)}>{k==='modelo'?'Modelo':k==='marca'?'Marca':'Sabor'}</button>)}</div></div>
  {(()=>{const list=(rankBy==='modelo'?[...r.rows].filter(p=>p.units).sort((a,b)=>b.units-a.units||b.revenue-a.revenue).map(p=>({key:p.id,name:p.model,detail:p.brand,units:p.units,revenue:p.revenue})):rankBy==='marca'?r.brands.map(b=>({...b,detail:`${r.rows.filter(p=>p.brand.trim().toLowerCase()===b.key&&p.units).length} modelo(s)`})):r.flavors).slice(0,rankBy==='sabor'?8:5);
   const max=Math.max(1,...list.map(x=>x.units));
   return list.length?list.map((x,i)=><div className="rank-row" key={x.key}><span className="rank-index">{String(i+1).padStart(2,'0')}</span><div><strong>{x.name}</strong><small>{x.detail}</small><div className="bar-track"><div style={{width:`${x.units/max*100}%`}}/></div></div><span><strong>{x.units} un.</strong><small>{brl(x.revenue)}</small></span></div>):<Empty text="Registre sua primeira venda para ver o ranking."/>;})()}
  <button className="text-button panel-link" onClick={()=>setSection('Relatórios')}>Ver relatório completo <ChevronRight size={15}/></button></section><section className="panel"><div className="panel-heading"><div><h2>Atenção ao estoque</h2><p>No mínimo ou abaixo dele</p></div><span className="badge warning">{r.low.length} variedades</span></div>{r.low.length?r.low.slice(0,5).map(v=><div className="low-row" key={v.id}><span className="product-icon"><Package size={18}/></span><div><strong>{data.products.find(p=>p.id===v.product_id)?.model}</strong><small>{v.name}</small></div><span className={`badge ${v.quantity===0?'danger':'warning'}`}>{v.quantity} un.</span></div>):<Empty text="Tudo em ordem com seu estoque."/>}<button className="text-button panel-link" onClick={()=>{setSection('Estoque');setStockStatus('baixo');}}>Conferir estoque <ArrowUpRight size={15}/></button></section></div>{r.loss>0&&<p className="hint">O resultado líquido inclui {brl(r.loss)} de perdas registradas em ajustes.</p>}</>}
 {section==='Estoque'&&<><div className="toolbar stock-toolbar"><label className="search"><Search size={18}/><input aria-label="Buscar produto ou sabor" placeholder="Buscar sabor, modelo ou marca…" value={query} onChange={e=>setQuery(e.target.value)}/></label>
  <label className="category-filter">Marca<select aria-label="Filtrar por marca" value={brand} onChange={e=>setBrand(e.target.value)}><option value="">Todas</option>{brandList.map(b=><option key={b}>{b}</option>)}</select></label>
  {categoryFilter()}
  <label className="category-filter">Situação<select aria-label="Filtrar por situação" value={stockStatus} onChange={e=>setStockStatus(e.target.value as typeof stockStatus)}><option value="todos">Todas</option><option value="com">Com estoque</option><option value="baixo">Estoque baixo</option><option value="esgotado">Esgotado</option></select></label>
  <span className="muted">{filtersOn?`${num(filteredUnits)} un. no filtro · `:''}{num(r.stock)} unidades no total{filtersOn&&<button className="text-button inline-clear" onClick={()=>{setQuery('');setBrand('');setCategory('');setStockStatus('todos');}}>Limpar filtros</button>}</span></div>
  {filteredProducts.map(p=><section className="panel product-panel" key={p.id}><div className="panel-heading"><div className="product-title"><span className="product-icon"><Package size={24}/></span><div><h2>{p.model}</h2><p>{p.brand} · {p.category} · Preço padrão {brl(p.price)}</p></div></div><button className="button secondary compact" onClick={()=>open('product',p)}>Editar produto</button></div><div className="table-wrap"><table><thead><tr><th>Sabor / variedade</th><th>Disponível</th><th>Mínimo</th><th>Custo médio</th><th>Capital</th><th>Situação</th></tr></thead><tbody>{visibleVariants(p).map(v=><tr key={v.id}><td><strong>{v.name}</strong></td><td>{v.quantity} un.</td><td>{p.minimum}</td><td>{brl(v.quantity?v.value/v.quantity:0)}</td><td>{brl(v.value)}</td><td><span className={`badge ${v.quantity===0?'danger':v.quantity<=p.minimum?'warning':'success'}`}>{v.quantity===0?'Esgotado':v.quantity<=p.minimum?'Estoque baixo':'Disponível'}</span></td></tr>)}</tbody></table></div></section>)}
  {!filteredProducts.length&&<Empty text={data.products.length?'Nenhum sabor corresponde aos filtros.':'Seu estoque está zerado. Comece por Entradas / Lotes → Nova compra.'}/>}</>}
 {section==='Entradas / Lotes'&&<>{[...data.batches].reverse().filter(b=>r.within(b.purchase_date??b.created_at)).map(b=>{const items=data.batch_items.filter(i=>i.batch_id===b.id);const other=b.other_costs??0;return <section className="panel batch-panel" key={b.id}><div className="panel-heading"><div><h2>Lote {b.number}{b.name&&b.name!==`Lote ${b.number}`?` — ${b.name}`:''}</h2><p>Compra em {dateBR(b.purchase_date??b.created_at)} · {items.reduce((a,i)=>a+i.quantity,0)} unidades · lançado em {dateBR(b.created_at)}</p></div><div className="batch-actions">{b.updated_at&&<span className="muted">editada em {dateBR(b.updated_at)}</span>}<span className="badge success">Finalizada</span><button className="button secondary compact" onClick={()=>open('batch',undefined,b)}>Editar compra</button></div></div><div className="batch-totals"><span>Mercadorias <strong>{brl(b.merchandise)}</strong></span><span>Frete <strong>{brl(b.freight)}</strong></span>{other>0&&<span>Outros custos <strong>{brl(other)}</strong></span>}<span>Custo total <strong>{brl(b.merchandise+b.freight+other)}</strong></span></div><details><summary>Ver itens, rateio e preços</summary><div className="table-wrap"><table><thead><tr><th>Produto / sabor</th><th>Qtd.</th><th>Custo un.</th><th>Frete rateado</th>{other>0&&<th>Outros</th>}<th>Custo efetivo un.</th><th>Custo médio após</th><th>Sugerido 47%</th><th>Preço definido</th></tr></thead><tbody>{items.map(i=>{const eff=i.effective_unit_cost??(i.quantity*i.unit_cost+i.freight+(i.other_costs??0))/i.quantity;return <tr key={i.id}><td>{label(data,i.variant_id)}</td><td>{i.quantity}</td><td>{brl(i.unit_cost)}</td><td>{brl(i.freight)}</td>{other>0&&<td>{brl(i.other_costs??0)}</td>}<td><strong>{brl(eff)}</strong></td><td>{i.avg_cost_after!=null?brl(i.avg_cost_after):'—'}</td><td>{i.suggested_price!=null?brl(i.suggested_price):'—'}</td><td>{i.sale_price!=null?brl(i.sale_price):'—'}</td></tr>;})}</tbody></table></div></details></section>;})}{!data.batches.some(b=>r.within(b.purchase_date??b.created_at))&&<Empty text={data.batches.length?'Nenhuma compra neste período.':'Nenhuma compra registrada. Clique em Nova compra para começar, mesmo com o estoque zerado.'}/>}</>}
 {section==='Vendas'&&<><div className="stock-metrics"><Metric title="Vendas no período" value={String(r.sales.length)}/><Metric title="Faturamento" value={brl(r.revenue)} detail="Produtos, já com descontos"/><Metric title="Descontos concedidos" value={brl(r.discounts)} detail={r.grossProducts?`${num(r.discounts/r.grossProducts*100)}% do valor de tabela`:'Sobre o preço de tabela'}/><Metric title="Lucro bruto" value={brl(r.gross)}/></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Venda / itens</th><th>Data</th><th>Pagamento</th><th>Produtos (tabela)</th><th>Desconto</th><th>Produtos (líquido)</th><th>Entrega cobrada</th><th>Custo da entrega</th><th>Resultado transporte</th><th>Taxa repassada</th><th>Total cobrado</th><th>Resultado da venda</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{[...r.sales].reverse().map(s=><tr key={s.id}><td><details><summary>Venda #{String(s.number).padStart(3,'0')}</summary><div className="sale-details">{data.sale_items.filter(i=>i.sale_id===s.id).map(i=><p key={i.id}>{i.quantity} × {label(data,i.variant_id)}<br/>{brl(i.unit_price)} un.{i.list_price!=null&&Math.abs(i.list_price-i.unit_price)>=0.005?` (tabela ${brl(i.list_price)})`:''}{(i.discount??0)>0?` · desconto ${brl(i.discount!)}`:''} · CMV {brl(i.cogs)}</p>)}{s.note&&<p>Obs.: {s.note}</p>}</div></details></td><td>{dateBR(s.created_at)}</td><td><span className="badge neutral">{s.payment}</span></td>{(()=>{const disc=data.sale_items.filter(i=>i.sale_id===s.id).reduce((a,i)=>a+itemDiscount(i),0);return <><td>{brl(s.revenue+disc)}</td><td className={disc>0?'negative':''}>{disc>0?`− ${brl(disc)}`:'—'}</td><td><strong>{brl(s.revenue)}</strong></td></>;})()}<td>{brl(s.delivery_charged??0)}</td><td>{brl(s.delivery_cost??0)}</td><td className={(s.delivery_charged??0)-(s.delivery_cost??0)>=0?'positive':'negative'}>{brl((s.delivery_charged??0)-(s.delivery_cost??0))}</td><td>{brl(s.card_fee)}</td><td>{brl(s.revenue+(s.delivery_charged??0)+s.card_fee)}</td><td className={s.revenue+(s.delivery_charged??0)-s.cogs-(s.delivery_cost??0)>=0?'positive':'negative'}>{brl(s.revenue+(s.delivery_charged??0)-s.cogs-(s.delivery_cost??0))}</td><td><button className="button secondary compact" onClick={()=>open('sale',undefined,undefined,s)}>Editar</button>{s.updated_at&&<small className="edited-tag">editada</small>}</td></tr>)}</tbody></table></div>{!r.sales.length&&<Empty text="Nenhuma venda neste período."/>}</section></>}
  {section==='Financeiro'&&(()=>{const c=cashFlow(data,from,to);const rows=[...c.rows].filter(x=>(!from||x.date>=from)&&(!to||x.date<=to)).filter(x=>finFilter==='tudo'||(finFilter==='despesas'?x.kind==='despesa':finFilter==='vendas'?x.kind==='venda':finFilter==='compras'?x.kind==='compra':finFilter==='emprestimos'?x.kind==='emprestimo'||x.kind==='pagamento_emprestimo':x.kind==='aporte'||x.kind==='retirada'||x.kind==='saldo_inicial')).reverse();
  const total=rows.reduce((a,x)=>a+x.amount,0);
  return <>
  <div className="stock-metrics"><Metric title="Saldo em caixa" value={brl(c.balance)} detail={c.start?`Desde ${dateBR(c.start)} · saldo inicial ${brl(c.opening)}`:'Lance o saldo inicial para começar'}/><Metric title="Empréstimos em aberto" value={brl(c.debt)} detail={c.loans.filter(l=>l.open>0).length?`${c.loans.filter(l=>l.open>0).length} empréstimo(s)`:'Nenhuma dívida'}/><Metric title="Entrou no período" value={brl(c.inflow)} detail="Vendas, empréstimos e aportes"/><Metric title="Saiu no período" value={brl(c.outflow)} detail="Compras, despesas, pagamentos e retiradas"/></div>
  {!c.start&&<p className="hint cash-note">Dica: comece por <strong>Novo lançamento → Saldo inicial</strong>, com o dinheiro que a empresa tinha em um dia.</p>}
  {c.loans.some(l=>l.open>0)&&<section className="panel"><div className="panel-heading"><div><h2>Empréstimos em aberto</h2><p>Não é faturamento; pagar o principal não é despesa (só os juros).</p></div></div><div className="table-wrap"><table><thead><tr><th>Empréstimo</th><th>Data</th><th>Valor</th><th>Pago</th><th>Em aberto</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{c.loans.filter(l=>l.open>0).map(l=><tr key={l.id}><td><strong>{l.description||'Empréstimo'}</strong></td><td>{dateBR(l.date)}</td><td>{brl(l.amount)}</td><td>{brl(l.paid)}</td><td><span className="badge warning">{brl(l.open)}</span></td><td><button className="button secondary compact" onClick={()=>{setCashPreset({kind:'pagamento_emprestimo',loan:l.id});open('cash');}}>Registrar pagamento</button></td></tr>)}</tbody></table></div></section>}
  <section className="panel"><div className="panel-heading"><div><h2>Movimentações</h2><p>Tudo o que entrou e saiu, com o saldo após cada lançamento.</p></div>
   <div className="segmented fin-filter" role="tablist" aria-label="Filtrar movimentações">{([['tudo','Tudo'],['despesas','Despesas'],['vendas','Vendas'],['compras','Compras'],['emprestimos','Empréstimos'],['aportes','Aportes e retiradas']] as const).map(([k,t])=><button key={k} role="tab" aria-selected={finFilter===k} className={finFilter===k?'active':''} onClick={()=>setFinFilter(k)}>{t}</button>)}</div></div>
   {finFilter!=='tudo'&&<p className="fin-total">{rows.length} lançamento(s) · total <strong className={total>=0?'positive':'negative'}>{total>=0?'+':'−'} {brl(Math.abs(total))}</strong></p>}
   <div className="table-wrap"><table><thead><tr><th>Data</th><th>Lançamento</th><th>Detalhe</th><th>Valor</th><th>Saldo</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{rows.map(x=><tr key={x.key}><td>{dateBR(x.date)}</td><td><strong>{x.label}</strong></td><td><small>{x.detail}</small></td><td className={x.amount>=0?'positive':'negative'}>{x.amount>=0?'+':'−'} {brl(Math.abs(x.amount))}</td><td>{x.balance===null?<small className="muted">antes do saldo inicial</small>:<strong>{brl(x.balance)}</strong>}</td>
    <td className="row-actions">{x.expense?(x.expense.source==='manual'?<><button className="button secondary compact" onClick={()=>open('expense',undefined,undefined,undefined,x.expense)}>Editar</button><button className={`button secondary compact danger-button${confirming===x.key?' confirming':''}`} onClick={()=>{if(confirming!==x.key){setConfirming(x.key);return;}setConfirming('');save('cancel_expense',{id:x.key});}}>{confirming===x.key?'Confirmar':'Excluir'}</button></>:<small className="muted">{x.expense.source==='venda'?'Edite na venda':'Edite o pagamento'}</small>)
     :x.ref?<button className={`button secondary compact danger-button${confirming===x.ref?' confirming':''}`} onClick={()=>{if(confirming!==x.ref){setConfirming(x.ref!);return;}setConfirming('');save('cancel_cash_entry',{id:x.ref});}}>{confirming===x.ref?'Confirmar':'Excluir'}</button>:null}</td></tr>)}</tbody></table></div>{!rows.length&&<Empty text="Nenhuma movimentação com esse filtro."/>}</section>
  <div className="report-notes"><h3>Caixa × resultado</h3><p>O <strong>resultado</strong> (Dashboard) mostra se você lucrou: venda − custo do produto − despesas. O <strong>caixa</strong> mostra quanto dinheiro existe: compras saem do caixa no dia em que são pagas (e viram estoque) e empréstimos entram no caixa (e viram dívida).</p></div>
 </>;})()}
 {section==='Relatórios'&&<><section className="panel"><div className="panel-heading"><div><h2>Performance de produtos</h2><p>Compare vendas, rentabilidade e movimento{category?` · categoria ${categoryList.find(c=>categoryKey(c.name)===category)?.name??''}`:''}.</p></div><div className="report-filters">{categoryFilter(true)}<label className="sort-label">Ordenar por<select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="units">Unidades vendidas</option><option value="revenue">Faturamento</option><option value="profit">Lucro bruto</option><option value="margin">Margem</option><option value="turnover">Giro</option></select></label></div></div><div className="table-wrap"><table className="performance"><thead><tr><th>Produto</th><th>Categoria</th><th>Unidades</th><th>Faturamento</th><th>Lucro bruto</th><th>Margem</th><th>Giro</th><th>Variedade líder</th><th>Última venda</th><th>Dias sem venda</th><th>Estoque atual</th></tr></thead><tbody>{ranking.map(p=><tr key={p.id}><td><strong>{p.model}</strong><small>{p.brand}</small></td><td><span className="badge neutral">{p.category}</span></td><td>{p.units}</td><td>{brl(p.revenue)}</td><td className={p.profit>=0?'positive':'negative'}>{brl(p.profit)}</td><td>{num(p.margin)}%</td><td>{p.turnover===null?'—':num(p.turnover)+'×'}</td><td>{p.best}</td><td>{p.last?dateBR(p.last):'Nunca'}</td><td>{p.days??'—'}</td><td>{p.stock} un.</td></tr>)}</tbody></table></div>{!ranking.length&&<Empty/>}</section><div className="report-notes"><h3>Como ler o relatório</h3><p>Vendas, lucro e variedade líder consideram o período selecionado. Última venda e dias sem venda consideram todo o histórico até hoje; estoque é a posição atual.</p><p>Giro = unidades vendidas ÷ média do estoque no início e no fim do período. “—” indica estoque médio zero. Lucro por produto não inclui entrega cobrada nem desconta despesas gerais. O transporte é separado no resultado abaixo.</p></div><section className="panel financial-report"><div className="panel-heading"><h2>Resultado do período</h2></div>{[['Produtos pelo preço de tabela',r.grossProducts],['Descontos concedidos',-r.discounts],['Faturamento (produtos líquidos)',r.revenue],['Custo das mercadorias vendidas (CMV)',-r.cogs],['Lucro bruto',r.gross],['Despesas operacionais',-r.operatingExpense],['Entregas cobradas dos clientes (repasse)',r.deliveryRevenue],['Custo das entregas',-r.deliveryCost],['Resultado do transporte',r.deliveryProfit],['Perdas em ajustes (sem correções)',-r.loss],['Lucro líquido',r.net]].map(([title,value])=><div key={title as string}><span>{title}</span><strong>{brl(value as number)}</strong></div>)}</section></>}
 {section==='Histórico'&&<><div className="toolbar"><label>Tipo de movimentação<select value={kind} onChange={e=>setKind(e.target.value)}>{['Todos','Entrada','Venda','Ajuste'].map(x=><option key={x}>{x}</option>)}</select></label><label className="search"><Search size={18}/><input aria-label="Buscar movimentação" placeholder="Buscar produto, variedade ou motivo…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Movimento</th><th>Produto / variedade</th><th>Data</th><th>Quantidade</th><th>Valor de custo</th><th>Motivo / referência</th></tr></thead><tbody>{[...data.movements].reverse().filter(m=>r.within(m.created_at)&&(kind==='Todos'||kind===m.kind)&&(label(data,m.variant_id)+' '+m.reason).toLowerCase().includes(query.toLowerCase())).map(m=><tr key={m.id}><td><span className={`movement-kind ${m.quantity>0?'positive':''}`}>{m.quantity>0?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>} {m.kind}{m.kind==='Ajuste'&&m.adjustment_type==='correcao'?' (correção)':''}</span></td><td>{label(data,m.variant_id)}</td><td>{dateBR(m.created_at)}</td><td>{m.quantity>0?'+':''}{m.quantity}</td><td>{brl(m.value)}</td><td>{m.reason}<small>{m.kind==='Entrada'?`Lote ${data.batches.find(b=>b.id===m.reference_id)?.number??'—'}`:m.kind==='Venda'?`Venda #${data.sales.find(s=>s.id===m.reference_id)?.number??'—'}`:m.reference_id.slice(0,8)}</small></td></tr>)}</tbody></table></div>{!data.movements.some(m=>r.within(m.created_at)&&(kind==='Todos'||kind===m.kind)&&(label(data,m.variant_id)+' '+m.reason).toLowerCase().includes(query.toLowerCase()))&&<Empty text="Nenhuma movimentação corresponde aos filtros."/>}</section></>}
 </>}
 <footer className="page-footer"><span>TKM SMOKE <span>Atitude na marca. Clareza na gestão.</span></span><span>Valores em reais · Horário de Brasília</span></footer></div></main>{notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}{modal==='batch'&&<PurchaseForm key={editingBatch?.id??'new'} data={data} mode={mode} batch={editingBatch} onSave={save} onClose={()=>setModal(null)} busy={busy} error={modalError}/>}{modal==='cash'&&<CashForm data={data} initialKind={cashPreset.kind} loanId={cashPreset.loan} onSave={save} onClose={()=>setModal(null)} busy={busy} error={modalError}/>}{modal==='whatsapp'&&<WhatsappList data={data} onSave={save} onClose={()=>setModal(null)} busy={busy} error={modalError}/>}{modal&&modal!=='batch'&&modal!=='whatsapp'&&modal!=='cash'&&<EntryForm key={modal+(editing?.id??'')+(editingSale?.id??'')+(editingExpense?.id??'')} type={modal} data={data} product={editing} sale={editingSale} expense={editingExpense} onSave={save} onClose={()=>setModal(null)} busy={busy} error={modalError}/>}</div>;
}
