'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,BarChart3,Boxes,Check,ChevronRight,Download,History,LayoutDashboard,LogOut,Package,Plus,RefreshCw,Search,ShoppingBag,Sparkles,TrendingUp,Truck,Wallet,X} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {Action,Batch,Data,Payload,Product,applyAction,brl,categories,categoryKey,dateBR,day,demoData,emptyData,exportCSV,label,num,report} from '@/lib/domain';
import {EntryForm,ModalType} from './forms';
import {PurchaseForm} from './purchase';
import Brand from './brand';
const sections=[['Dashboard',LayoutDashboard],['Estoque',Boxes],['Entradas / Lotes',Truck],['Vendas',ShoppingBag],['Despesas',Wallet],['Relatórios',BarChart3],['Histórico',History]] as const;
type Section=typeof sections[number][0];
const descriptions:Record<Section,string>={Dashboard:'Tudo o que importa, em um só lugar.',Estoque:'Cada produto, cada variedade, sempre à mão.','Entradas / Lotes':'Toda reposição começa aqui: compra, produtos e estoque.',Vendas:'Suas vendas, do primeiro item ao resultado.',Despesas:'Saiba para onde vai o dinheiro do negócio.',Relatórios:'Descubra quais produtos fazem a diferença.',Histórico:'Um registro de cada movimento do seu estoque.'};
const DEMO_KEY='clara-demo-v1';
function Metric({title,value,detail,accent=false}:{title:string;value:string;detail?:string;accent?:boolean}) {return <div className={`metric ${accent?'accent':''}`}><span>{title}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;}
function Empty({text='Nenhum registro por aqui ainda.'}:{text?:string}) {return <div className="empty"><Package size={28}/><p>{text}</p></div>;}
export default function Workspace() {
 const [data,setData]=useState<Data>(emptyData());const [mode,setMode]=useState<'loading'|'login'|'demo'|'live'>('loading');const [section,setSection]=useState<Section>('Dashboard');
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [authBusy,setAuthBusy]=useState(false);
 const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);
 const [modal,setModal]=useState<ModalType|null>(null);const [editing,setEditing]=useState<Product>();const [editingBatch,setEditingBatch]=useState<Batch>();const [modalError,setModalError]=useState('');
 const [from,setFrom]=useState('');const [to,setTo]=useState('');const [query,setQuery]=useState('');const [lowOnly,setLowOnly]=useState(false);const [category,setCategory]=useState('');const [kind,setKind]=useState('Todos');
 const [sort,setSort]=useState<'units'|'revenue'|'profit'|'margin'|'turnover'>('units');const [expenseFilter,setExpenseFilter]=useState('Todas');
 const pending=useRef<string|null>(null);const saving=useRef(false);const mounted=useRef(true);
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);try{const {data:state,error:e}=await supabase.rpc('get_state');if(e)throw e;if(mounted.current)setData(state as Data);}finally{if(mounted.current)setLoading(false);}},[]);
 useEffect(()=>{mounted.current=true;if(!supabase){setMode('login');return;}supabase.auth.getSession().then(async({data:{session},error:e})=>{if(e)setError(e.message);if(!mounted.current)return;setMode(session?'live':'login');if(session)try{await load();}catch(e){setError((e as Error).message);}});const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){setData(emptyData());setMode('login');}if(event==='SIGNED_IN'&&session)setMode('live');});return()=>{mounted.current=false;subscription.unsubscribe();};},[load]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(timer);},[notice]);
 const r=useMemo(()=>report(data,from,to),[data,from,to]);
 function open(type:ModalType,product?:Product,batch?:Batch){pending.current=null;setModalError('');setEditing(product);setEditingBatch(batch);setModal(type);}
 function startDemo(){try{const saved=localStorage.getItem(DEMO_KEY);setData(saved?JSON.parse(saved):demoData());setMode('demo');setError('');}catch{setData(demoData());setMode('demo');setNotice('Uma nova demonstração foi iniciada.');}}
 async function login(e:React.FormEvent){e.preventDefault();if(!supabase)return;setAuthBusy(true);setError('');try{const {error:e}=await supabase.auth.signInWithPassword({email,password});if(e)throw e;setPassword('');setMode('live');await load();}catch(e){setError((e as Error).message);}finally{setAuthBusy(false);}}
 async function logout(){if(mode==='live'&&supabase){const {error:e}=await supabase.auth.signOut();if(e){setError(e.message);return;}}setData(emptyData());setMode('login');setError('');}
 async function save(action:Action,p:Payload):Promise<boolean>{if(saving.current)return false;saving.current=true;setBusy(true);setModalError('');const request_id=pending.current??crypto.randomUUID();pending.current=request_id;
  try{if(mode==='demo'){const next=applyAction(data,action,{...p,request_id});localStorage.setItem(DEMO_KEY,JSON.stringify(next));setData(next);}else{if(!supabase)throw Error('Supabase não configurado.');const {error:e}=await supabase.rpc(action,{p:{...p,request_id}});if(e)throw e;try{await load();}catch{setError('Registro salvo, mas a atualização da tela falhou. Clique em Atualizar antes de continuar.');}}
   setModal(null);pending.current=null;setNotice(({record_purchase:'Compra finalizada. Estoque e custos atualizados.',update_purchase:'Compra corrigida. Estoque e custos recalculados.',rename_purchase:'Nome e data da compra atualizados.',delete_purchase:'Compra excluída. Estoque atualizado.'} as Record<string,string>)[action]??'Registro salvo com sucesso.');return true;
  }catch(e){setModalError((e as Error).message);return false;}finally{saving.current=false;setBusy(false);}}
 async function refresh(){setError('');try{await load();setNotice('Dados atualizados.');}catch(e){setError((e as Error).message);}}
 function period(value:string){const today=day();setTo(today);if(value==='all'){setFrom('');setTo('');}else if(value==='month')setFrom(today.slice(0,7)+'-01');else{const d=new Date(today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-29);setFrom(day(d));}}
 const categoryList=categories(data.products);const inCategory=(c:string)=>!category||categoryKey(c||'Geral')===category;
 const filteredProducts=data.products.filter(p=>inCategory(p.category)).filter(p=>(p.brand+' '+p.model+' '+p.category).toLowerCase().includes(query.toLowerCase())||data.variants.some(v=>v.product_id===p.id&&v.name.toLowerCase().includes(query.toLowerCase())));
 const ranking=[...r.rows].filter(p=>inCategory(p.category)).sort((a,b)=>(b[sort]??-1)-(a[sort]??-1));
 const csv=()=>exportCSV(ranking.map(p=>({Produto:p.model,Marca:p.brand,Categoria:p.category,Unidades:p.units,Faturamento:brl(p.revenue),Lucro:brl(p.profit),'Margem (%)':num(p.margin),Giro:p.turnover===null?'—':num(p.turnover),'Variedade mais vendida':p.best,'Última venda':p.last?dateBR(p.last):'Nunca','Dias sem venda':p.days??'—','Estoque atual':p.stock})),`performance-${category?categoryKey(category).replace(/\s+/g,'-')+'-':''}${day()}.csv`);
 const categoryFilter=(compact=false)=> <label className={compact?'sort-label':'category-filter'}>Categoria<select aria-label="Filtrar por categoria" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas ({data.products.length})</option>{categoryList.map(c=><option key={c.name} value={categoryKey(c.name)}>{c.name} ({c.count})</option>)}</select></label>;
 if(mode==='loading')return <main className="loading"><RefreshCw className="spin"/><p>Abrindo seu espaço…</p></main>;
 if(mode==='login')return <main className="login-page"><section className="login-story"><div className="login-signature"><span className="brand-name">TKM SMOKE</span><span className="login-system-label">ESTOQUE & FINANCEIRO</span></div><div className="login-brand-stage"><Brand hero/></div><div className="login-story-copy"><span className="eyebrow">ATITUDE NA MARCA. CLAREZA NA GESTÃO.</span><h1>Seu negócio.<br/> Seu controle.</h1><p>Estoque, vendas e resultados.<br/>Tudo no mesmo lugar.</p></div><small>TKM SMOKE <span>•</span> Seu espaço de gestão.</small></section><section className="login-panel"><div><span className="eyebrow">BEM-VINDA À TKM SMOKE</span><h2>Acesse seu espaço.</h2><p className="muted">Entre com a conta compartilhada do seu negócio.</p>{supabase?<form onSubmit={login}><label>E-mail<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com"/></label><label>Senha<input type="password" autoComplete="current-password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button wide" disabled={authBusy}>{authBusy?'Entrando…':'Entrar no meu espaço'}<ArrowUpRight size={17}/></button></form>:<div className="setup-note">O ambiente está pronto para demonstração. Para usar dados reais, configure o Supabase conforme o guia do projeto.</div>}{error&&<p className="error" role="alert">{error}</p>}<div className="or"><span/>ou conheça primeiro<span/></div><button className="button secondary wide" onClick={startDemo}><Sparkles size={17}/>Explorar demonstração</button><p className="hint centered">Papelaria fictícia · Dados salvos apenas neste navegador</p></div></section></main>;
 return <div className="app-shell"><aside className="sidebar"><Brand/><div className="workspace-label"><span className="avatar">{mode==='demo'?'D':'T'}</span><div><strong>{mode==='demo'?'Demonstração':'TKM SMOKE'}</strong><small>{mode==='demo'?'Ambiente de demonstração':'Estoque e financeiro'}</small></div></div><span className="nav-label">ESPAÇO DE TRABALHO</span><nav aria-label="Menu principal">{sections.map(([name,Icon])=><button key={name} aria-label={name} title={name} className={section===name?'selected':''} onClick={()=>{setSection(name);setQuery('');}} aria-current={section===name?'page':undefined}><Icon size={19}/><span>{name}</span>{section===name&&<span className="active-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><span className="status-dot"/><span>{mode==='demo'?'Demonstração local':'Conectado ao Supabase'}</span></div><button onClick={logout}><LogOut size={17}/>Sair do espaço</button></div></aside>
 <main className="main"><header className="topbar"><div><span className="breadcrumb">TKM SMOKE</span><ChevronRight size={14}/><strong>{section}</strong></div><div className="topbar-right"><span>{dateBR(day())}</span>{mode==='live'&&<button className="icon-button" disabled={loading} onClick={refresh} aria-label="Atualizar dados"><RefreshCw size={17} className={loading?'spin':''}/></button>}<button className="icon-button" onClick={logout} aria-label="Sair"><LogOut size={16}/></button><span className="avatar small">{mode==='demo'?'D':'T'}</span></div></header>
 <div className="page-content">{mode==='demo'&&<div className="demo-banner"><Sparkles size={16}/><span>Você está explorando uma papelaria fictícia. Alterações ficam neste navegador.</span><button onClick={()=>{localStorage.removeItem(DEMO_KEY);setData(demoData());setNotice('Demonstração reiniciada.');}}>Reiniciar demo</button></div>}
 <div className="page-heading"><div><span className="eyebrow">{section==='Dashboard'?'VISÃO GERAL':'GESTÃO DO NEGÓCIO'}</span><h1>{section==='Dashboard'?'Seu negócio em foco.':section}</h1><p>{descriptions[section]}</p></div><div className="actions">{section==='Estoque'?<><button className="button secondary" onClick={()=>open('adjust')} disabled={!data.variants.length}>Ajustar estoque</button><button className="button secondary" onClick={()=>open('product')}><Plus size={17}/>Novo produto</button><button className="button" onClick={()=>open('batch')}><Truck size={17}/>Nova compra</button></>:section==='Relatórios'?<button className="button secondary" onClick={csv} disabled={!ranking.length}><Download size={16}/>Exportar CSV</button>:section!=='Histórico'&&<button className="button" onClick={()=>open(section==='Entradas / Lotes'?'batch':section==='Despesas'?'expense':'sale')}><Plus size={17}/>{section==='Entradas / Lotes'?'Nova compra':section==='Despesas'?'Nova despesa':'Nova venda'}</button>}</div></div>
 {error&&<div className="error" role="alert">{error}<button className="icon-button" aria-label="Fechar aviso" onClick={()=>setError('')}><X size={16}/></button></div>}
 {section!=='Estoque'&&<div className="period-bar"><span>Período</span><button onClick={()=>period('all')} className={!from&&!to?'period-active':''}>Tudo</button><button onClick={()=>period('month')}>Este mês</button><button onClick={()=>period('30')}>30 dias</button><div className="date-range"><input aria-label="Data inicial" type="date" value={from} max={to||undefined} onChange={e=>setFrom(e.target.value)}/><span>até</span><input aria-label="Data final" type="date" value={to} min={from||undefined} onChange={e=>setTo(e.target.value)}/></div></div>}
 {from&&to&&from>to?<div className="error">A data inicial deve ser anterior à data final.</div>:<>
 {section==='Dashboard'&&<><div className="hero-grid"><div className="result-card"><div><span>Resultado líquido do período</span><span className="hero-icon"><TrendingUp size={21}/></span></div><strong>{brl(r.net)}</strong><p>Depois dos custos, despesas e perdas em ajustes.</p><footer><span>Margem líquida <b>{num(r.revenue?r.net/r.revenue*100:0)}%</b></span><span>{num(r.units)} unidades vendidas</span></footer></div><div className="metrics-grid"><Metric title="Faturamento" value={brl(r.revenue)} detail="Produtos + entregas cobradas"/><Metric title="Lucro bruto" value={brl(r.gross)} detail="Faturamento − custo vendido"/><Metric title="Despesas" value={brl(r.expense)} detail="Lançamentos no período"/><Metric title="Capital recuperado" value={brl(r.cogs)} detail="Custo das mercadorias vendidas"/></div></div>
 <div className="section-heading"><h2>Transporte no período</h2><span>Receita e custo vinculados às vendas</span></div><div className="stock-metrics three"><Metric title="Entrega cobrada dos clientes" value={brl(r.deliveryRevenue)} detail="Incluída no faturamento"/><Metric title="Custo das entregas" value={brl(r.deliveryCost)} detail="Incluído em despesas, uma única vez"/><Metric title="Resultado do transporte" value={brl(r.deliveryProfit)} detail={r.deliveryProfit>=0?'Receita de entrega menos custo':'Custo maior que o valor cobrado'}/></div>
 <div className="section-heading"><h2>Seu estoque, agora</h2><span>Posição atual · independente do período</span></div><div className="stock-metrics"><Metric title="Unidades em estoque" value={num(r.stock)} detail={`${data.products.length} produtos · ${data.variants.length} variedades`}/><Metric title="Capital em estoque" value={brl(r.capital)} detail="Custo médio com frete"/><Metric title="Venda potencial" value={brl(r.potential)} detail="Aos preços padrão atuais"/><Metric title="Lucro bruto potencial" value={brl(r.potential-r.capital)} detail="Antes de futuras despesas"/></div>
 <div className="bottom-grid"><section className="panel"><div className="panel-heading"><div><h2>Produtos em destaque</h2><p>Mais vendidos no período</p></div><button className="text-button" onClick={()=>setSection('Relatórios')}>Ver relatório <ChevronRight size={15}/></button></div>{r.rows.some(p=>p.units)?[...r.rows].sort((a,b)=>b.units-a.units).filter(p=>p.units).slice(0,5).map((p,i)=><div className="rank-row" key={p.id}><span className="rank-index">0{i+1}</span><div><strong>{p.model}</strong><small>{p.brand}</small><div className="bar-track"><div style={{width:`${p.units/Math.max(...r.rows.map(x=>x.units))*100}%`}}/></div></div><span><strong>{p.units} un.</strong><small>{brl(p.revenue)}</small></span></div>):<Empty text="Registre sua primeira venda para ver os destaques."/>}</section><section className="panel"><div className="panel-heading"><div><h2>Atenção ao estoque</h2><p>No mínimo ou abaixo dele</p></div><span className="badge warning">{r.low.length} variedades</span></div>{r.low.length?r.low.slice(0,5).map(v=><div className="low-row" key={v.id}><span className="product-icon"><Package size={18}/></span><div><strong>{data.products.find(p=>p.id===v.product_id)?.model}</strong><small>{v.name}</small></div><span className={`badge ${v.quantity===0?'danger':'warning'}`}>{v.quantity} un.</span></div>):<Empty text="Tudo em ordem com seu estoque."/>}<button className="text-button panel-link" onClick={()=>{setSection('Estoque');setLowOnly(true);}}>Conferir estoque <ArrowUpRight size={15}/></button></section></div>{r.loss>0&&<p className="hint">O resultado líquido inclui {brl(r.loss)} de perdas registradas em ajustes.</p>}</>}
 {section==='Estoque'&&<><div className="toolbar"><label className="search"><Search size={18}/><input aria-label="Buscar produto ou variedade" placeholder="Buscar produto, marca ou variedade…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{categoryFilter()}<label className="check-filter"><input type="checkbox" checked={lowOnly} onChange={e=>setLowOnly(e.target.checked)}/>Somente estoque baixo</label><span className="muted">{category?`${num(filteredProducts.reduce((a,p)=>a+data.variants.filter(v=>v.product_id===p.id).reduce((b,v)=>b+v.quantity,0),0))} un. nesta categoria · `:''}{num(r.stock)} unidades no total</span></div>{filteredProducts.filter(p=>!lowOnly||data.variants.some(v=>v.product_id===p.id&&v.quantity<=p.minimum)).map(p=><section className="panel product-panel" key={p.id}><div className="panel-heading"><div className="product-title"><span className="product-icon"><Package size={24}/></span><div><h2>{p.model}</h2><p>{p.brand} · {p.category} · Preço padrão {brl(p.price)}</p></div></div><button className="button secondary compact" onClick={()=>open('product',p)}>Editar produto</button></div><div className="table-wrap"><table><thead><tr><th>Sabor / variedade</th><th>Disponível</th><th>Mínimo</th><th>Custo médio</th><th>Capital</th><th>Situação</th></tr></thead><tbody>{data.variants.filter(v=>v.product_id===p.id&&(!lowOnly||v.quantity<=p.minimum)).map(v=><tr key={v.id}><td><strong>{v.name}</strong></td><td>{v.quantity} un.</td><td>{p.minimum}</td><td>{brl(v.quantity?v.value/v.quantity:0)}</td><td>{brl(v.value)}</td><td><span className={`badge ${v.quantity===0?'danger':v.quantity<=p.minimum?'warning':'success'}`}>{v.quantity===0?'Esgotado':v.quantity<=p.minimum?'Estoque baixo':'Disponível'}</span></td></tr>)}</tbody></table></div></section>)}{(!filteredProducts.length||(lowOnly&&!filteredProducts.some(p=>data.variants.some(v=>v.product_id===p.id&&v.quantity<=p.minimum))))&&<Empty text={data.products.length?'Nenhum produto corresponde aos filtros.':'Seu estoque está zerado. Comece por Entradas / Lotes → Nova compra.'}/>}</>}
 {section==='Entradas / Lotes'&&<>{[...data.batches].reverse().filter(b=>r.within(b.purchase_date??b.created_at)).map(b=>{const items=data.batch_items.filter(i=>i.batch_id===b.id);const other=b.other_costs??0;return <section className="panel batch-panel" key={b.id}><div className="panel-heading"><div><h2>Lote {b.number}{b.name&&b.name!==`Lote ${b.number}`?` — ${b.name}`:''}</h2><p>Compra em {dateBR(b.purchase_date??b.created_at)} · {items.reduce((a,i)=>a+i.quantity,0)} unidades · lançado em {dateBR(b.created_at)}</p></div><div className="batch-actions">{b.updated_at&&<span className="muted">editada em {dateBR(b.updated_at)}</span>}<span className="badge success">Finalizada</span><button className="button secondary compact" onClick={()=>open('batch',undefined,b)}>Editar compra</button></div></div><div className="batch-totals"><span>Mercadorias <strong>{brl(b.merchandise)}</strong></span><span>Frete <strong>{brl(b.freight)}</strong></span>{other>0&&<span>Outros custos <strong>{brl(other)}</strong></span>}<span>Custo total <strong>{brl(b.merchandise+b.freight+other)}</strong></span></div><details><summary>Ver itens, rateio e preços</summary><div className="table-wrap"><table><thead><tr><th>Produto / sabor</th><th>Qtd.</th><th>Custo un.</th><th>Frete rateado</th>{other>0&&<th>Outros</th>}<th>Custo efetivo un.</th><th>Custo médio após</th><th>Sugerido 47%</th><th>Preço definido</th></tr></thead><tbody>{items.map(i=>{const eff=i.effective_unit_cost??(i.quantity*i.unit_cost+i.freight+(i.other_costs??0))/i.quantity;return <tr key={i.id}><td>{label(data,i.variant_id)}</td><td>{i.quantity}</td><td>{brl(i.unit_cost)}</td><td>{brl(i.freight)}</td>{other>0&&<td>{brl(i.other_costs??0)}</td>}<td><strong>{brl(eff)}</strong></td><td>{i.avg_cost_after!=null?brl(i.avg_cost_after):'—'}</td><td>{i.suggested_price!=null?brl(i.suggested_price):'—'}</td><td>{i.sale_price!=null?brl(i.sale_price):'—'}</td></tr>;})}</tbody></table></div></details></section>;})}{!data.batches.some(b=>r.within(b.purchase_date??b.created_at))&&<Empty text={data.batches.length?'Nenhuma compra neste período.':'Nenhuma compra registrada. Clique em Nova compra para começar, mesmo com o estoque zerado.'}/>}</>}
 {section==='Vendas'&&<><div className="stock-metrics three"><Metric title="Vendas no período" value={String(r.sales.length)}/><Metric title="Faturamento" value={brl(r.revenue)}/><Metric title="Lucro bruto" value={brl(r.gross)}/></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Venda / itens</th><th>Data</th><th>Pagamento</th><th>Produtos</th><th>Entrega cobrada</th><th>Custo da entrega</th><th>Resultado transporte</th><th>Taxa repassada</th><th>Total cobrado</th><th>Resultado da venda</th></tr></thead><tbody>{[...r.sales].reverse().map(s=><tr key={s.id}><td><details><summary>Venda #{String(s.number).padStart(3,'0')}</summary><div className="sale-details">{data.sale_items.filter(i=>i.sale_id===s.id).map(i=><p key={i.id}>{i.quantity} × {label(data,i.variant_id)}<br/>{brl(i.unit_price)} un. · CMV {brl(i.cogs)}</p>)}{s.note&&<p>Obs.: {s.note}</p>}</div></details></td><td>{dateBR(s.created_at)}</td><td><span className="badge neutral">{s.payment}</span></td><td>{brl(s.revenue)}</td><td>{brl(s.delivery_charged??0)}</td><td>{brl(s.delivery_cost??0)}</td><td className={(s.delivery_charged??0)-(s.delivery_cost??0)>=0?'positive':'negative'}>{brl((s.delivery_charged??0)-(s.delivery_cost??0))}</td><td>{brl(s.card_fee)}</td><td>{brl(s.revenue+(s.delivery_charged??0)+s.card_fee)}</td><td className={s.revenue+(s.delivery_charged??0)-s.cogs-(s.delivery_cost??0)>=0?'positive':'negative'}>{brl(s.revenue+(s.delivery_charged??0)-s.cogs-(s.delivery_cost??0))}</td></tr>)}</tbody></table></div>{!r.sales.length&&<Empty text="Nenhuma venda neste período."/>}</section></>}
 {section==='Despesas'&&<><div className="stock-metrics three"><Metric title="Total de despesas" value={brl(r.expense)}/><Metric title="Anúncios" value={brl(r.expenses.filter(e=>e.category==='Anúncios').reduce((a,e)=>a+e.amount,0))} detail="Lançamentos manuais"/><Metric title="Lançamentos no período" value={String(r.expenses.length)}/></div><div className="toolbar"><label>Filtrar categoria<select value={expenseFilter} onChange={e=>setExpenseFilter(e.target.value)}>{['Todas','Anúncios','Entrega','Embalagem','Ferramentas/sistemas','Outros'].map(x=><option key={x}>{x}</option>)}</select></label></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Descrição</th><th>Categoria</th><th>Data</th><th>Origem</th><th>Valor</th></tr></thead><tbody>{[...r.expenses].reverse().filter(e=>expenseFilter==='Todas'||e.category===expenseFilter).map(e=><tr key={e.id}><td><strong>{e.description}</strong></td><td><span className="badge neutral">{e.category}</span></td><td>{dateBR(e.date)}</td><td>{e.source==='manual'?'Manual':e.source==='venda'?`Venda #${data.sales.find(s=>s.id===e.sale_id)?.number??'—'}`:e.source}</td><td>{brl(e.amount)}</td></tr>)}</tbody></table></div>{!r.expenses.some(e=>expenseFilter==='Todas'||e.category===expenseFilter)&&<Empty text="Nenhuma despesa corresponde aos filtros."/>}</section></>}
 {section==='Relatórios'&&<><section className="panel"><div className="panel-heading"><div><h2>Performance de produtos</h2><p>Compare vendas, rentabilidade e movimento{category?` · categoria ${categoryList.find(c=>categoryKey(c.name)===category)?.name??''}`:''}.</p></div><div className="report-filters">{categoryFilter(true)}<label className="sort-label">Ordenar por<select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="units">Unidades vendidas</option><option value="revenue">Faturamento</option><option value="profit">Lucro bruto</option><option value="margin">Margem</option><option value="turnover">Giro</option></select></label></div></div><div className="table-wrap"><table className="performance"><thead><tr><th>Produto</th><th>Categoria</th><th>Unidades</th><th>Faturamento</th><th>Lucro bruto</th><th>Margem</th><th>Giro</th><th>Variedade líder</th><th>Última venda</th><th>Dias sem venda</th><th>Estoque atual</th></tr></thead><tbody>{ranking.map(p=><tr key={p.id}><td><strong>{p.model}</strong><small>{p.brand}</small></td><td><span className="badge neutral">{p.category}</span></td><td>{p.units}</td><td>{brl(p.revenue)}</td><td className={p.profit>=0?'positive':'negative'}>{brl(p.profit)}</td><td>{num(p.margin)}%</td><td>{p.turnover===null?'—':num(p.turnover)+'×'}</td><td>{p.best}</td><td>{p.last?dateBR(p.last):'Nunca'}</td><td>{p.days??'—'}</td><td>{p.stock} un.</td></tr>)}</tbody></table></div>{!ranking.length&&<Empty/>}</section><div className="report-notes"><h3>Como ler o relatório</h3><p>Vendas, lucro e variedade líder consideram o período selecionado. Última venda e dias sem venda consideram todo o histórico até hoje; estoque é a posição atual.</p><p>Giro = unidades vendidas ÷ média do estoque no início e no fim do período. “—” indica estoque médio zero. Lucro por produto não inclui entrega cobrada nem desconta despesas gerais. O transporte é separado no resultado abaixo.</p></div><section className="panel financial-report"><div className="panel-heading"><h2>Resultado do período</h2></div>{[['Receita de produtos',r.productRevenue],['Receita de entregas',r.deliveryRevenue],['Faturamento total',r.revenue],['Custo das mercadorias vendidas (CMV)',-r.cogs],['Lucro bruto',r.gross],['Despesas (exceto entregas vinculadas)',-(r.expense-r.deliveryCost)],['Custos das entregas vinculadas',-r.deliveryCost],['Perdas em ajustes de estoque',-r.loss],['Lucro líquido',r.net]].map(([title,value])=><div key={title as string}><span>{title}</span><strong>{brl(value as number)}</strong></div>)}</section></>}
 {section==='Histórico'&&<><div className="toolbar"><label>Tipo de movimentação<select value={kind} onChange={e=>setKind(e.target.value)}>{['Todos','Entrada','Venda','Ajuste'].map(x=><option key={x}>{x}</option>)}</select></label><label className="search"><Search size={18}/><input aria-label="Buscar movimentação" placeholder="Buscar produto, variedade ou motivo…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Movimento</th><th>Produto / variedade</th><th>Data</th><th>Quantidade</th><th>Valor de custo</th><th>Motivo / referência</th></tr></thead><tbody>{[...data.movements].reverse().filter(m=>r.within(m.created_at)&&(kind==='Todos'||kind===m.kind)&&(label(data,m.variant_id)+' '+m.reason).toLowerCase().includes(query.toLowerCase())).map(m=><tr key={m.id}><td><span className={`movement-kind ${m.quantity>0?'positive':''}`}>{m.quantity>0?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>} {m.kind}</span></td><td>{label(data,m.variant_id)}</td><td>{dateBR(m.created_at)}</td><td>{m.quantity>0?'+':''}{m.quantity}</td><td>{brl(m.value)}</td><td>{m.reason}<small>{m.kind==='Entrada'?`Lote ${data.batches.find(b=>b.id===m.reference_id)?.number??'—'}`:m.kind==='Venda'?`Venda #${data.sales.find(s=>s.id===m.reference_id)?.number??'—'}`:m.reference_id.slice(0,8)}</small></td></tr>)}</tbody></table></div>{!data.movements.some(m=>r.within(m.created_at)&&(kind==='Todos'||kind===m.kind)&&(label(data,m.variant_id)+' '+m.reason).toLowerCase().includes(query.toLowerCase()))&&<Empty text="Nenhuma movimentação corresponde aos filtros."/>}</section></>}
 </>}
 <footer className="page-footer"><span>TKM SMOKE <span>Atitude na marca. Clareza na gestão.</span></span><span>Valores em reais · Horário de Brasília</span></footer></div></main>{notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}{modal==='batch'&&<PurchaseForm key={editingBatch?.id??'new'} data={data} mode={mode} batch={editingBatch} onSave={save} onClose={()=>setModal(null)} busy={busy} error={modalError}/>}{modal&&modal!=='batch'&&<EntryForm key={modal+(editing?.id??'')} type={modal} data={data} product={editing} onSave={save} onClose={()=>setModal(null)} busy={busy} error={modalError}/>}</div>;
}
